"""new fields in user model

Revision ID: 43070ff7ead7
Revises: 15193c059fa4
Create Date: 2017-12-29 17:39:36.717037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43070ff7ead7'
down_revision = '15193c059fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
